# Generated by Django 2.2.5 on 2019-11-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255, unique=True, verbose_name='prefix')),
                ('organization', models.CharField(max_length=255, verbose_name='organization')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Vendor OUI',
                'verbose_name_plural': 'Vendor OUIs',
                'db_table': 'oui_oui',
                'ordering': ['prefix'],
            },
        ),
    ]
