# Generated by Django 2.2.5 on 2019-10-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminListDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('AdminListDisplayAdmin', 'AdminListDisplayAdmin')], max_length=255, verbose_name='model')),
                ('field', models.CharField(max_length=255, verbose_name='field')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name': 'Admin List Display',
                'verbose_name_plural': 'Admin List Display',
                'db_table': 'utility_admin_list_display',
                'ordering': ['model', 'order'],
                'unique_together': {('model', 'field'), ('model', 'order')},
            },
        ),
    ]
