# Generated by Django 2.2.5 on 2019-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0002_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnetV4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('subnet_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Subnet IP')),
                ('cidr', models.PositiveSmallIntegerField(verbose_name='CIDR')),
                ('starting_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Starting IP')),
                ('ending_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Ending IP')),
                ('gateway_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Gateway IP')),
                ('broadcast_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Broadcast IP')),
            ],
            options={
                'verbose_name': 'Subnet version 4',
                'verbose_name_plural': 'Subnets version 4',
                'db_table': 'netscanner_subnet_v4',
                'ordering': ['name'],
            },
        ),
    ]
