# Generated by Django 2.2.5 on 2019-10-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0006_domain_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscanner.DomainMain', verbose_name='domain')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'netscanner_domain',
                'ordering': ['domain', 'name'],
                'unique_together': {('domain', 'name')},
            },
        ),
    ]
