# Generated by Django 2.2.5 on 2019-10-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0008_operating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscanner.Brand', verbose_name='brand')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscanner.DeviceType', verbose_name='device type')),
            ],
            options={
                'verbose_name': 'Device model',
                'verbose_name_plural': 'Device models',
                'db_table': 'netscanner_device_model',
                'ordering': ['device_type', 'brand', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
    ]
