# Generated by Django 2.2.5 on 2019-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0010_custom_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tool', models.CharField(max_length=255, verbose_name='tool')),
            ],
            options={
                'verbose_name': 'Scanner',
                'verbose_name_plural': 'Scanners',
                'db_table': 'netscanner_scanner',
                'ordering': ['name'],
            },
        ),
    ]
