# Generated by Django 2.2.5 on 2019-10-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0012_discovery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discovery',
            name='arguments',
        ),
        migrations.AddField(
            model_name='discovery',
            name='options',
            field=models.TextField(blank=True, verbose_name='options'),
        ),
    ]
