# Generated by Django 2.2.5 on 2019-10-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0013_discovery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='options',
            field=models.TextField(blank=True, verbose_name='options'),
        ),
    ]
