# Generated by Django 2.2.5 on 2019-10-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0015_unique_on_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='area')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='position')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('mac_address', models.CharField(blank=True, max_length=12, verbose_name='MAC address')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='hostname')),
                ('serial', models.CharField(blank=True, max_length=255, verbose_name='serial number')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('no_discovery', models.BooleanField(default=False, verbose_name='do not update on discoveries')),
                ('last_seen', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last seen')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verification', models.DateField(blank=True, default=None, null=True, verbose_name='verification')),
                ('snmp_version', models.CharField(blank=True, choices=[('v1', '1'), ('v2c', '2C')], max_length=5, verbose_name='SNMP version')),
                ('snmp_community', models.CharField(blank=True, max_length=5, verbose_name='SNMP community string')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.Company', verbose_name='company')),
                ('custom_fields', models.ManyToManyField(blank=True, db_table='netscanner_host_custom', to='netscanner.CustomField', verbose_name='custom fields')),
                ('device_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.DeviceModel', verbose_name='device model')),
                ('domain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.Domain', verbose_name='network domain')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.Location', verbose_name='location')),
                ('os', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.OperatingSystem', verbose_name='operating system')),
                ('subnetv4', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.SubnetV4', verbose_name='subnet v4')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'db_table': 'netscanner_hosts',
                'ordering': ['location', 'name', 'address'],
                'unique_together': {('location', 'name', 'address')},
            },
        ),
    ]
