# Generated by Django 2.2.5 on 2019-10-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0016_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'ordering': ['brand', 'name'], 'verbose_name': 'Device model', 'verbose_name_plural': 'Device models'},
        ),
    ]
