# Generated by Django 2.2.5 on 2019-10-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0018_discovery_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='interval',
            field=models.PositiveIntegerField(default=60, verbose_name='scan interval'),
        ),
    ]
