# Generated by Django 2.2.5 on 2019-10-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0022_snmp_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('oid', models.CharField(max_length=255, verbose_name='OID')),
                ('format', models.CharField(blank=True, max_length=255, verbose_name='format string')),
                ('trim', models.BooleanField(default=False, verbose_name='trim spaces')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscanner.Brand', verbose_name='brand')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscanner.SNMPSection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'SNMP Value',
                'verbose_name_plural': 'SNMP Values',
                'db_table': 'netscanner_snmp_value',
                'ordering': ['section', 'brand', 'name'],
                'unique_together': {('section', 'brand', 'name')},
            },
        ),
    ]
