# Generated by Django 2.2.5 on 2019-10-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0023_snmp_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('values', models.ManyToManyField(blank=True, db_table='netscanner_snmp_configuration_values', to='netscanner.SNMPValue', verbose_name='SNMP values')),
            ],
            options={
                'verbose_name': 'SNMP Configuration',
                'verbose_name_plural': 'SNMP Configurations',
                'db_table': 'netscanner_snmp_configuration',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='snmp_configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.SNMPConfiguration', verbose_name='SNMP configuration'),
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.SNMPConfiguration', verbose_name='SNMP configuration'),
        ),
    ]
