# Generated by Django 2.2.5 on 2019-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0024_snmp_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='snmp_community',
            field=models.CharField(blank=True, max_length=255, verbose_name='SNMP community string'),
        ),
    ]
