# Generated by Django 2.2.5 on 2019-10-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0025_host_snmp_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='snmp_version',
            field=models.CharField(blank=True, choices=[('off', 'Off'), ('v1', '1'), ('v2c', '2C')], max_length=5, verbose_name='SNMP version'),
        ),
    ]
