# Generated by Django 2.2.5 on 2019-10-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0027_snmp_configuration_autodetect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snmpconfiguration',
            options={'ordering': ['device_model', 'name'], 'verbose_name': 'SNMP Configuration', 'verbose_name_plural': 'SNMP Configurations'},
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='snmp_configuration',
        ),
        migrations.RemoveField(
            model_name='snmpconfiguration',
            name='autodetect_value',
        ),
        migrations.AddField(
            model_name='snmpconfiguration',
            name='device_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.DeviceModel', verbose_name='Device model'),
        ),
        migrations.AddField(
            model_name='snmpconfiguration',
            name='format',
            field=models.CharField(blank=True, max_length=255, verbose_name='Format string'),
        ),
        migrations.AddField(
            model_name='snmpconfiguration',
            name='lstrip',
            field=models.BooleanField(default=False, verbose_name='Strip spaces on the left'),
        ),
        migrations.AddField(
            model_name='snmpconfiguration',
            name='rstrip',
            field=models.BooleanField(default=False, verbose_name='Strip spaces on the right'),
        ),
        migrations.AddField(
            model_name='snmpconfiguration',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='Resulting value'),
        ),
        migrations.AlterField(
            model_name='snmpconfiguration',
            name='autodetect',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snmp_configuration_autodetect', to='netscanner.SNMPValue', verbose_name='Autodetect value'),
        ),
    ]
