# Generated by Django 2.2.5 on 2019-10-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0028_snmp_configuration_autodetect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snmpvalue',
            name='trim',
        ),
        migrations.AddField(
            model_name='snmpvalue',
            name='lstrip',
            field=models.BooleanField(default=False, verbose_name='Strip spaces on the left'),
        ),
        migrations.AddField(
            model_name='snmpvalue',
            name='rstrip',
            field=models.BooleanField(default=False, verbose_name='Strip spaces on the right'),
        ),
    ]
