# Generated by Django 2.2.5 on 2019-10-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0030_discovery_result_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpconfiguration',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Resulting value'),
        ),
    ]
