# Generated by Django 2.2.5 on 2019-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0031_snmp_configuration_value_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='image'),
        ),
    ]
