# Generated by Django 2.2.5 on 2019-11-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0033_snmp_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='snmp_version',
            new_name='snmp_version_text',
        ),
        migrations.AddField(
            model_name='host',
            name='snmp_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.SNMPVersion', verbose_name='SNMP version'),
        ),
        migrations.RunSQL(
            "UPDATE netscanner_hosts "
            "SET snmp_version_id = ( "
            "  SELECT id "
            "  FROM netscanner_snmp_version "
            "  WHERE version = 0 "
            "  LIMIT 0, 1"
            ") "
            "WHERE snmp_version_text = 'off'",
        ),
        migrations.RunSQL(
            "UPDATE netscanner_hosts "
            "SET snmp_version_id = ( "
            "  SELECT id "
            "  FROM netscanner_snmp_version "
            "  WHERE version = 1 "
            "  LIMIT 0, 1"
            ") "
            "WHERE snmp_version_text = 'v1'",
        ),
        migrations.RunSQL(
            "UPDATE netscanner_hosts "
            "SET snmp_version_id = ( "
            "  SELECT id "
            "  FROM netscanner_snmp_version "
            "  WHERE version = 2 "
            "  LIMIT 0, 1"
            ") "
            "WHERE snmp_version_text = 'v2c'",
        ),
        migrations.RemoveField(
            model_name='host',
            name='snmp_version_text',
        ),
    ]
