# Generated by Django 2.2.5 on 2019-11-04 16:04

import socket
import struct

from django.db import migrations, models, transaction


def set_address_numeric(apps, schema_editor):
    # Don't import the Host model directly as it may be a newer version
    # than this migration expects. Using the historical version.
    Host = apps.get_model('netscanner', 'Host')
    # Rewrite all the hosts to update the address_numeric field
    with transaction.atomic():
        for host in Host.objects.all():
            host.address_numeric = struct.unpack(
                '!I',
                socket.inet_aton(host.address))[0]
            host.save()


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0035_device_model_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['location', 'address_numeric'], 'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AddField(
            model_name='host',
            name='address_numeric',
            field=models.IntegerField(default=0, editable=False, verbose_name='address in numeric form'),
        ),
        migrations.RunPython(set_address_numeric)
    ]
