# Generated by Django 2.2.5 on 2019-11-05 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0036_host_address_numeric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='custom_fields',
        ),
        migrations.CreateModel(
            name='HostCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.CustomField', verbose_name='field')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netscanner.Host', verbose_name='host')),
            ],
            options={
                'verbose_name': 'Host Custom field',
                'verbose_name_plural': 'Hosts Custom fields',
                'db_table': 'netscanner_host_custom_fields',
                'ordering': ['host', 'field'],
                'unique_together': {('host', 'field')},
            },
        ),
    ]
