# Generated by Django 2.2.5 on 2019-11-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0037_host_custom_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Host (extended)',
                'verbose_name_plural': 'Hosts (extended)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('netscanner.host',),
        ),
    ]
