# Generated by Django 2.2.5 on 2019-11-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0038_host_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpconfiguration',
            name='values',
            field=models.ManyToManyField(blank=True, db_table='netscanner_snmp_configuration_values_set', to='netscanner.SNMPValue', verbose_name='SNMP values'),
        ),
        migrations.CreateModel(
            name='SNMPConfigurationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=255, verbose_name='field')),
                ('snmp_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netscanner.SNMPConfiguration', verbose_name='configuration')),
                ('snmp_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snmp_configuration_value_values', to='netscanner.SNMPValue', verbose_name='value')),
            ],
            options={
                'verbose_name': 'SNMP Configuration value',
                'verbose_name_plural': 'SNMP Configuration values',
                'db_table': 'netscanner_snmp_configuration_values',
                'ordering': ['snmp_configuration', 'snmp_value'],
                'unique_together': {('snmp_configuration', 'snmp_value')},
            },
        ),
        migrations.RunSQL(
            "INSERT INTO netscanner_snmp_configuration_values "
            "(snmp_configuration_id, snmp_value_id, field) "
            "SELECT "
            "  snmpconfiguration_id, "
            "  snmpvalue_id, "
            "  '' "
            "FROM netscanner_snmp_configuration_values_set ",
        ),
        migrations.RemoveField(
            model_name='snmpconfiguration',
            name='values',
        ),
    ]
