# Generated by Django 2.2.5 on 2019-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0039_snmp_configuration_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpconfigurationvalue',
            name='text_values',
            field=models.TextField(blank=True, verbose_name='JSON text values'),
        ),
    ]
