# Generated by Django 2.2.5 on 2019-11-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0040_snmp_configuration_value_text_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='os/', verbose_name='image'),
        ),
    ]
