# Generated by Django 2.2.5 on 2020-04-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netscanner', '0041_operating_system_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetv4',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='netscanner_subnet_v4_hosts', to='netscanner.Host', verbose_name='Manual hosts list'),
        ),
    ]
